### ISSUE TITLE
add keyrings

### ISSUE THREAD

**Issue by mattsb42-aws** [aws/aws-encryption-sdk-python#146]
Starting with the AWS Encryption SDK for C, we moved from master keys/providers to keyrings as a configuration/framework primitive. We need to add corresponding keyrings to this client as well.

In order to maintain backwards compatibility, we need to retain the existing MKP framework and support the use of MKPs within the new keyring framework. After discussing several options, we decided that the best route to accomplish this is with a MKP keyring.

This MKP keyring will take a MKP as input and provide the MK/MKP management logic currently in `DefaultCryptoMaterialsManager`, along with necessary keyring logic (ex: adding keyring traces), all wrapped up in the new keyring interface.

As a temporary measure, in order to enable end-to-end keyring tests without tackling the MKP keyring and the updates to `DefaultCryptoMaterialsManager`, we will need to make a `KeyringDefaultCryptoMaterialsManager` that handles the signing/verification keys but only understands keyrings.

All keyring development PRs should be made to the `keyring` branch.

- [x] Updated cryptographic materials to meet keyring needs [pr: #163]
- [x] Make updated encryption materials immutable [issue: #214]
- [x] `KeyringTraceFlag` does not need to be value/name-compatible with C [issue: #215]
- [x] Keyring interface [pr: #161]
- [x] AWS KMS keyring [issue: #212] [pr: #218]
- [x] Raw RSA keyring [pr: #165]
- [x] Raw AES keyring [pr: #165]
- [x] Multi keyring [pr: #166]
- [x] Enable keyring use. [issue: #211] [pr: #216]
- [x] Migration guide for users [issue: #213]
